package ma.enova.radio.workflow.admin.process.prescriptionradiotherapie.suivreconsultation;

import ma.enova.radio.zynerator.process.AbstractProcess;
import ma.enova.radio.bean.core.PrescriptionRadiotherapie;

public interface PrescriptionRadiotherapieSuivreConsultationAdminProcess extends AbstractProcess<PrescriptionRadiotherapieSuivreConsultationAdminInput, PrescriptionRadiotherapieSuivreConsultationAdminOutput, PrescriptionRadiotherapie> {
}
