package ma.enova.radio.workflow.admin.process.prescriptionradiotherapie.validatephysicien;

import ma.enova.radio.zynerator.process.AbstractProcess;
import ma.enova.radio.bean.core.PrescriptionRadiotherapie;

public interface PrescriptionRadiotherapieValidatePhysicienAdminProcess extends AbstractProcess<PrescriptionRadiotherapieValidatePhysicienAdminInput, PrescriptionRadiotherapieValidatePhysicienAdminOutput, PrescriptionRadiotherapie> {
}
